version: "3.3"

services:
  # api:
  #   build: .
  #   container_name: api-rmc
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - src/main/config/env/.dev.env
  psql:
    image: postgres:latest
    container_name: psql-rmc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rate-my-code
    volumes:
      - app-psql-volume

  redis:
    image: redis:latest
    container_name: redis-rmc
    ports:
      - "6379:6379"
    volumes:
      - app-redis-volume

  mongo:
    image: mongo:latest
    container_name: mongo-rmc
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rate-my-code
    volumes:
      - app-mongo-volume

volumes:
  app-psql-volume:
  app-redis-volume:
  app-mongo-volume:
